name       : gtk2-engine-murrine
version    : 0.98.2
release    : 5
source     :
    - https://download.gnome.org/sources/murrine/0.98/murrine-0.98.2.tar.xz : e9c68ae001b9130d0f9d1b311e8121a94e5c134b82553ba03971088e57d12c89
license    : GPL-2.0+
component  : desktop.theme
summary    : Murrine Engine for GTK2 Themes
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig32(gtk+-2.0)
    - pkgconfig(pango)
    - pkgconfig32(pango)
    - pkgconfig(cairo)
    - pkgconfig32(cairo)
    - pkgconfig(atk)
    - pkgconfig32(atk)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    Murrine Engine for GTK2 Themes
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make V=1
install    : |
    %make_install
