name        : gtk2-engine-murrine
version     : 0.98.2
release     : 3
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/murrine/0.98/murrine-0.98.2.tar.xz : e9c68ae001b9130d0f9d1b311e8121a94e5c134b82553ba03971088e57d12c89
license     : GPL-2.0+
summary     : Murrine Engine for GTK2 Themes
builddeps   :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(pango)
    - pkgconfig(cairo)
    - pkgconfig(atk)
description : |
    Murrine Engine for GTK2 Themes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
